import csv
import math
from dataclasses import dataclass
from typing import List, Tuple


@dataclass
class CenterlinePoint:
    """
    One waypoint from centerline_points_smooth.csv.

    The CSV is produced by centerline_tools and contains:
    [index, x, y, yaw, curvature, curvature_abs]
    """
    index: int
    x: float
    y: float
    yaw: float
    curvature: float
    curvature_abs: float


def load_centerline_csv(csv_path: str) -> List[CenterlinePoint]:
    """
    Load centerline CSV generated by centerline_tools.

    Returns:
        A list of CenterlinePoint objects in driving order.
    """
    points: List[CenterlinePoint] = []

    with open(csv_path, "r") as f:
        reader = csv.DictReader(f)

        required_columns = [
            "index",
            "x",
            "y",
            "yaw",
            "curvature",
            "curvature_abs",
        ]

        for col in required_columns:
            if col not in reader.fieldnames:
                raise ValueError(
                    f"Missing required column '{col}'. "
                    f"Found columns: {reader.fieldnames}"
                )

        for row in reader:
            points.append(
                CenterlinePoint(
                    index=int(row["index"]),
                    x=float(row["x"]),
                    y=float(row["y"]),
                    yaw=float(row["yaw"]),
                    curvature=float(row["curvature"]),
                    curvature_abs=float(row["curvature_abs"]),
                )
            )

    if len(points) < 10:
        raise ValueError(f"Centerline too short: only {len(points)} points loaded.")

    return points


def wrap_angle(angle: float) -> float:
    """
    Wrap angle to [-pi, pi].
    """
    while angle > math.pi:
        angle -= 2.0 * math.pi
    while angle < -math.pi:
        angle += 2.0 * math.pi
    return angle


def get_loop_index(index: int, size: int) -> int:
    """
    Wrap an index around a closed-loop centerline.
    Example:
        -1 becomes size - 1
        size becomes 0
    """
    return index % size


def find_nearest_centerline_index(
    x: float,
    y: float,
    centerline: List[CenterlinePoint],
) -> int:
    """
    Find the nearest centerline waypoint to the vehicle position.

    This simple O(N) search is fine for now because the centerline has only
    hundreds or a few thousand points. Later we can replace it with KD-tree.
    """
    best_idx = 0
    best_dist_sq = float("inf")

    for i, p in enumerate(centerline):
        dx = x - p.x
        dy = y - p.y
        dist_sq = dx * dx + dy * dy

        if dist_sq < best_dist_sq:
            best_dist_sq = dist_sq
            best_idx = i

    return best_idx


def compute_cross_track_error(
    car_x: float,
    car_y: float,
    nearest_point: CenterlinePoint,
) -> float:
    """
    Compute signed lateral error relative to the nearest centerline point.

    Positive/negative sign is based on the centerline heading:
        tangent = [cos(yaw), sin(yaw)]
        left normal = [-sin(yaw), cos(yaw)]

    If error > 0:
        car is on the left side of centerline direction.
    If error < 0:
        car is on the right side of centerline direction.
    """
    dx = car_x - nearest_point.x
    dy = car_y - nearest_point.y

    left_normal_x = -math.sin(nearest_point.yaw)
    left_normal_y = math.cos(nearest_point.yaw)

    return dx * left_normal_x + dy * left_normal_y


def compute_heading_error(
    car_yaw: float,
    nearest_point: CenterlinePoint,
) -> float:
    """
    Compute vehicle heading error relative to centerline yaw.

    0 means the vehicle is aligned with the local centerline direction.
    """
    return wrap_angle(car_yaw - nearest_point.yaw)


def get_upcoming_curvature_abs(
    nearest_idx: int,
    centerline: List[CenterlinePoint],
    lookahead_points: int = 20,
) -> float:
    """
    Estimate upcoming curve severity.

    For speed control, we do not only care about curvature at the nearest point.
    We care about the road shape slightly ahead of the car.

    This function returns the maximum curvature_abs over the next N points.
    """
    n = len(centerline)
    max_curv = 0.0

    for offset in range(lookahead_points + 1):
        idx = get_loop_index(nearest_idx + offset, n)
        max_curv = max(max_curv, centerline[idx].curvature_abs)

    return max_curv



def _segment_distance(centerline: List[CenterlinePoint], from_idx: int, to_idx: int) -> float:
    """Distance between two wrapped neighboring centerline indices."""
    n = len(centerline)
    p0 = centerline[get_loop_index(from_idx, n)]
    p1 = centerline[get_loop_index(to_idx, n)]
    return math.hypot(p1.x - p0.x, p1.y - p0.y)


def get_preview_end_offset_by_distance(
    nearest_idx: int,
    centerline: List[CenterlinePoint],
    preview_distance_m: float,
) -> int:
    """Return the forward waypoint offset closest to a metric preview distance.

    This mirrors path_following_v2/path_generator_node.cpp: walk forward along
    the closed raceline and choose the waypoint offset whose accumulated arc
    length is nearest to the requested preview boundary.  A preview distance of
    0 uses the nearest waypoint only.
    """
    n = len(centerline)
    if n <= 1 or preview_distance_m <= 0.0:
        return 0

    preview_distance_m = float(preview_distance_m)
    accumulated = 0.0
    end_offset = 0

    for offset in range(1, n):
        previous_idx = get_loop_index(nearest_idx + offset - 1, n)
        idx = get_loop_index(nearest_idx + offset, n)
        next_accumulated = accumulated + _segment_distance(centerline, previous_idx, idx)

        if next_accumulated >= preview_distance_m:
            # Choose whichever boundary is closer: previous offset or current offset.
            if abs(next_accumulated - preview_distance_m) < abs(preview_distance_m - accumulated):
                end_offset = offset
            break

        accumulated = next_accumulated
        end_offset = offset

    return int(end_offset)


def get_upcoming_curvature_abs_by_distance(
    nearest_idx: int,
    centerline: List[CenterlinePoint],
    preview_distance_m: float,
) -> float:
    """Maximum abs curvature from nearest_idx to a metric preview distance.

    This is the metre-based counterpart of get_upcoming_curvature_abs(...,
    lookahead_points=N) and is intended to match the rule-speed preview in
    path_following_v2.
    """
    n = len(centerline)
    end_offset = get_preview_end_offset_by_distance(nearest_idx, centerline, preview_distance_m)
    max_curv = 0.0
    for offset in range(end_offset + 1):
        idx = get_loop_index(nearest_idx + offset, n)
        max_curv = max(max_curv, max(0.0, centerline[idx].curvature_abs))
    return float(max_curv)


def get_curvature_abs_section_average_by_distance(
    nearest_idx: int,
    centerline: List[CenterlinePoint],
    start_distance_m: float,
    end_distance_m: float,
) -> float:
    """Average abs curvature over a forward metric section.

    The section is [start_distance_m, end_distance_m] measured along the closed
    raceline from nearest_idx.  If no waypoint center falls in the requested
    section, the function falls back to the max-curvature preview at end_distance_m
    so that reward computation remains well-defined.
    """
    n = len(centerline)
    if n == 0:
        return 0.0

    start_distance_m = max(0.0, float(start_distance_m))
    end_distance_m = max(start_distance_m, float(end_distance_m))

    values = []
    accumulated = 0.0

    for offset in range(n):
        idx = get_loop_index(nearest_idx + offset, n)
        if accumulated >= start_distance_m and accumulated <= end_distance_m:
            values.append(max(0.0, centerline[idx].curvature_abs))

        if accumulated > end_distance_m:
            break

        next_idx = get_loop_index(nearest_idx + offset + 1, n)
        accumulated += _segment_distance(centerline, idx, next_idx)

    if values:
        return float(sum(values) / len(values))

    return get_upcoming_curvature_abs_by_distance(nearest_idx, centerline, end_distance_m)


def compute_centerline_progress_delta(
    previous_idx: int,
    current_idx: int,
    centerline_size: int,
) -> int:
    """
    Compute forward progress in waypoint-index units on a closed loop.

    Example:
        previous_idx = 630
        current_idx = 5
        centerline_size = 634

    Then progress should be:
        9 points forward, not -625.
    """
    if previous_idx is None:
        return 0

    raw_delta = current_idx - previous_idx

    # Handle wrap-around at the end/start of the closed loop.
    if raw_delta < -centerline_size / 2:
        raw_delta += centerline_size
    elif raw_delta > centerline_size / 2:
        raw_delta -= centerline_size

    return raw_delta


def get_centerline_state_features(
    car_x: float,
    car_y: float,
    car_yaw: float,
    car_speed: float,
    centerline: List[CenterlinePoint],
    curvature_lookahead_points: int = 20,
) -> Tuple[List[float], int]:
    """
    Build the minimal RL observation features.

    Returns:
        features:
            [
                car_speed,
                cross_track_error,
                heading_error,
                upcoming_curvature_abs,
            ]

        nearest_idx:
            nearest centerline index, useful for progress reward later.
    """
    nearest_idx = find_nearest_centerline_index(car_x, car_y, centerline)
    nearest_point = centerline[nearest_idx]

    cross_track_error = compute_cross_track_error(
        car_x,
        car_y,
        nearest_point,
    )

    heading_error = compute_heading_error(
        car_yaw,
        nearest_point,
    )

    upcoming_curvature_abs = get_upcoming_curvature_abs(
        nearest_idx,
        centerline,
        lookahead_points=curvature_lookahead_points,
    )

    features = [
        float(car_speed),
        float(cross_track_error),
        float(heading_error),
        float(upcoming_curvature_abs),
    ]

    return features, nearest_idx